services:
  acme.action_applier.pattern:
    class: TheAkademy\RuleActionBundle\ActionApplier\PatternActionApplier
    arguments:
      - '@pim_catalog.updater.property_setter'
    tags:
      - { name: akeneo_rule_engine.action_applier, priority: 100 }

  acme.denormalizer.product_rule.pattern_action:
    class: TheAkademy\RuleActionBundle\Denormalizer\ProductRule\PatternActionDenormalizer
    tags:
      - { name: 'pimee_catalog_rule.denormalizer.product_rule' }

  acme.validator.existing_attributes:
    class: TheAkademy\RuleActionBundle\Validator\Constraints\ExistingAttributesValidator
    arguments:
      - '@pim_catalog.repository.attribute'
    tags:
      - { name: validator.constraint_validator, alias: pimee_constraint_attributes_validator }